theme: jekyll-theme-cayman
title: Gemstone.Data
description: GPA Gemstone Data Library
github:
  repository_name: Gemstone.Data
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
